name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: ["ghc-9.0"]

jobs:
  cabal:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]  # TODO: add macOS/Windows
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        cabal-version: "3.2"
        ghc-version: "9.0.0.20201227"
    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.cabal
        key: ${{ runner.os }}
    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks --allow-newer="Cabal"
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all
    - name: Run tests
      run: cabal test all
